### ISSUE TITLE
VS2015 paths

### ISSUE THREAD

**Issue by elburz** [kylemcdonald/ofxCv#199]
Seems a bit difficult to get this compiling currently on Windows, needing to setup multiple paths for the compiling and linking, at least took me a while to get it up and running. 

How can I best help remedy that for new users? I have VS2015 project with relatives path setup using the empteExample based, if we want to add an empty project to the repo that is ready to accept the src files from any of the examples or I can add the paths I'm using to the readme.md under where you have the Mac header path listed, but they're quite long (possibly some of them aren't needed as well). Let me know your prefs.

**Comment by elburz** [comment]
Not sure if its related or not, but using the VS oF plugin, it does add some of the paths, is that something we can update so that it adds the paths? I'm not quite sure how the VS oF plugin works.

**Comment by ch3gr** [comment]
Did you try using the project generator that comes with OF for VS?

**Comment by mruegenberg** [comment]
I just tested running a ofxCv project on windows using the project generator. I got it working  (after adressing #205 through renaming) by adding both ofxCv and ofxOpenCv to my addons.make (presumably the OpenCV lib itself is not added otherwise. Not sure if the Windows project generator properly handles `addon_config.mk`, which should do this automatically.)

**Comment by kylemcdonald** [comment]
Going to close this. If it's an recurring problem it should be reported to the project generator repo.
